security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                #provider: fos_userbundle
                #csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                check_path: /login_check

                # l'utilisateur est redirigé ici si il/elle a besoin de se connecter
                login_path: /login

                # si true, l'utilisateur est envoyé au formulaire de connexion et non redirigé
                use_forward: false

                # Les options de redirection en cas de succès de connexion (lire plus bas)
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false

                # Les options de redirection en cas d'échec de connexion (lire plus bas)
                #failure_path:    /foo
                #failure_forward: false
                #failure_path_parameter: _failure_path
                #failure_handler: some.service.id
                #success_handler: some.service.id

                # le nom des champs username et password
                username_parameter: _username
                password_parameter: _password

                # les options du token csrf
                csrf_parameter: _csrf_token
                intention:      authenticate
                csrf_provider:  security.csrf.token_manager

                # par défautt, le formulaire de connextion *doit* être de type POST et non GET
                post_only:      true
                remember_me:    false

                # par défaut, une session doit exister avant de soumettre une requête d'authentification
                # si false, alors Request::hasPreviousSession n'est pas appelé durant l'authentification
                # nouveau dans Symfony 2.3
                require_previous_session: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
        