## YAML Template.
---
ItechSup\Bundle\QuestionnaireBundle\Entity\Utilisateur:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
