#Zservices:
#    itech_sup_questionnaire.example:
#        class: ItechSup\Bundle\QuestionnaireBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


services:
    acme_main.menu_builder:
        class: ItechSup\Bundle\QuestionnaireBundle\Menu\Builder
        arguments: ['@knp_menu.factory', '@doctrine.orm.entity_manager']
        
    acme_main.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: acme_main.menu_builder
        factory_method: createMainMenu
        tags:
            - { name: knp_menu.menu, alias: main }
